services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: "${VITE_API_URL:-http://localhost:3000}"
