backend:
  build:
    context: ../PruebaTecnicaModuloGestionPromociones-Backend
    dockerfile: Dockerfile

  environment:
    NODE_ENV: production

    DB_HOST: sqlserver
    DB_PORT: "1433"
    DB_USER: sa
    DB_PASSWORD: "${DB_PASSWORD}"
    DB_NAME: PromocionesDB

    DB_USE_WINDOWS_AUTH: "false"
    DB_ENCRYPT: "true"
    DB_TRUST_SERVER_CERTIFICATE: "true"
    DB_SYNCHRONIZE: "false"
    DB_LOGGING: "true"

  ports:
    - "3000:3000"

  depends_on:
    sqlserver:
      condition: service_healthy