services:

  sqlserver:
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Promociones#Nueva2026!"
      MSSQL_PID: "Developer"

  backend:
    environment:
      NODE_ENV: production

      DB_HOST: sqlserver
      DB_PORT: 1433
      DB_USER: sa
      DB_PASSWORD: "Promociones#Nueva2026!"
      DB_NAME: DBGestionPromociones

      DB_USE_WINDOWS_AUTH: "false"
      DB_ENCRYPT: "true"
      DB_TRUST_SERVER_CERTIFICATE: "true"
      DB_SYNCHRONIZE: "false"
      DB_LOGGING: "true"

  frontend:
    build:
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:3000}